(require 'url)
(defvar iciba-url "http://dict-co.iciba.com/search.php"
  "爱词霸 翻译 api 接口")  
(defun translate-icb ()
  "Translate en-cn cn-en"
  (interactive)
  (let* ((word (or (thing-at-point 'word) (read-string "Translate-icb> "))))
    (let ((url-request-method "GET")
	  (foo (concat "?word=" (url-hexify-string word)
		       "&submit=" (url-hexify-string "查询"))))
      (with-current-buffer (url-retrieve-synchronously (concat iciba-url foo))
	
	(progn
	  (goto-char (point-min))
	  (re-search-forward "body" nil 'move)
	  (re-search-forward ">" nil 'move)  
	  (delete-region (point) (point-min))
	  (goto-char (point-min))
	  (while  (re-search-forward "<" nil 'move)
	    (progn
	      (forward-char -1)
	      (setq beg (point))
	      (re-search-forward ">" nil 'move)
	      (setq end (point))
	      (delete-region beg end)
	      (goto-char (point-min))
	      )
	    )
	  
	  (goto-char (point-min))
	  (while (re-search-forward "&nbsp;" nil 'move)
	    (replace-match " ")
	    )
	  (re-search-forward "返回查词首页" nil t)
	  (setq end (point))
	  (forward-char -25)
	  (delete-region (point) end)

	  (goto-char (point-min))
	  (re-search-forward "[a-z]" nil 'move)
	  (forward-char -1)
	  (delete-region (point) (point-min))
	  (message (decode-coding-string (buffer-string) 'utf-8))
	  )
	)
      )
    )
  )
(global-set-key "\C-c\ \C-f" 'translate-icb)
(provide 'translate-icb)
